# Armor Stand Tools v2.0
#
# by St3venAU (St3venAU@gmail.com)
#
# Features:
#   - Summon armor stands
#   - Name armor stands
#   - Toggle: Gravity, Visibility, Arms, Base, Size, Invulnerability, Equipment Lock
#   - Manipulate the position of the Head, Body, Arms and Legs
#   - Full control over armor stand's inventory (armor & item in hand)
#   - Clone armor stand tool
#   - Create command block tool: Creates a command block with the command that will summon this
#     armor stand in its current state
#   - Player head tool: Set's an armor stand's head to the head of a specified player.
#   - Support for WorldGuard regions.
#   - User customizable language config.
#
# Commands:
#   /astools          Give yourself all of the armor stand tools (Note: Clears your inventory)
#   /astools reload   Reload the armor stand tools plugin config file
#   /ast              Alias for the /astools
#
# Permissions:
#   astools.command   Permission for the /astools command
#   astools.reload    Permission to reload the plugin with /astools reload
#   astools.use       Permission for using any of the tools (except the ones below)
#   astools.clone     Permission to use the clone tool
#   astools.cmdblock  Permission to use the save tool (Creates a command block)
#
# These are the defaults for spawning new armor stands with the /astools (or /ast) armor stand
# The helmet, chest, pants, boots and inHand items are set like this: MATERIAL dataValue
# e.g. To have red wool in the armor stands hand by default: inHand: WOOL 14
#
integrateWithWorldGuard: true
helmet: SKULL_ITEM 3
chest: IRON_CHESTPLATE 0
pants: IRON_LEGGINGS 0
boots: IRON_BOOTS 0
inHand: AIR 0
isVisible: true
isSmall: false
hasArms: true
hasBasePlate: false
hasGravity: false
name: ''
invulnerable: false
equipmentLock: false