main: com.gmail.St3venAU.plugins.ArmorStandTools.Main
name: ArmorStandTools
version: 2.03
author: St3venAU
description: Armor stand manipulation tools
softdepend: [WorldGuard, PlotSquared]
commands:
   astools:
      description: Give yourself the armor stand tools
      aliases: ast
      usage: Usage /astools or /astools reload