main: com.gmail.St3venAU.plugins.ArmorStandTools.Main
name: ArmorStandTools
version: 1.7
author: St3venAU
description: Armor stand manipulation tools
softdepend: [WorldGuard]
commands:
   astools:
      description: Give yourself all of the armor stand tools (Warning; clears your inventory).
      aliases: ast
      usage: Usage /astools or /astools reload or /astools head